### ISSUE TITLE
Error while adding schema link to Shopify GraphQL api

### ISSUE THREAD

**Issue by iamHrithikRaj** [LeapYear/graphql-client#73]
so my `codegen.yml` looks something like this

```yaml

schema: https://{MY_STORE_NAME}.myshopify.com/api/2022-07/graphql.json
documents: src/XXX/GraphQL/api/*.graphql

# hsSourceDir: src/
apiModule: XXX.GraphQL.API
enumsModule: XXX.GraphQL.Enums
scalarsModule: XXX.GraphQL.Scalars
```

but when I try to run `stack exec graphql-codegen` it throws this error

```
FetchError: invalid json response body at https://{MY_STORE_NAME}.myshopify.com/api/2022-10/graphql.json reason: Unexpected end of JSON input
    at /private/var/folders/_n/vrt8yb952kz_bfppbgh8jw3w0000gn/T/graphql-codegen-1f017550460301f2/graphql-codegen-haskell.js:31536:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async introspectSchema (/private/var/folders/_n/vrt8yb952kz_bfppbgh8jw3w0000gn/T/graphql-codegen-1f017550460301f2/graphql-codegen-haskell.js:35651:33)
    at async UrlLoader.getSubschemaConfig (/private/var/folders/_n/vrt8yb952kz_bfppbgh8jw3w0000gn/T/graphql-codegen-1f017550460301f2/graphql-codegen-haskell.js:41201:21)
    at async UrlLoader.load (/private/var/folders/_n/vrt8yb952kz_bfppbgh8jw3w0000gn/T/graphql-codegen-1f017550460301f2/graphql-codegen-haskell.js:41207:33)
    at async loadFile (/private/var/folders/_n/vrt8yb952kz_bfppbgh8jw3w0000gn/T/graphql-codegen-1f017550460301f2/graphql-codegen-haskell.js:30658:24)
    at async /private/var/folders/_n/vrt8yb952kz_bfppbgh8jw3w0000gn/T/graphql-codegen-1f017550460301f2/graphql-codegen-haskell.js:30917:24 {
  type: 'invalid-json'
}
graphql-codegen: Received ExitFailure 1 when running
Raw command: node /private/var/folders/_n/vrt8yb952kz_bfppbgh8jw3w0000gn/T/graphql-codegen-1f017550460301f2/graphql-codegen-haskell.js /Users/hrithikraj/Documents/Projects/XXX/XXX/codegen.yml
```
